env:
  matrix:
    - SCHEME="ChezScheme_master"
    - SCHEME="Guile_2.2"
    - SCHEME="Larceny"
    - SCHEME="Racket_HEAD"
    - SCHEME="SagittariusScheme"
    - SCHEME="VicareScheme"
    - SCHEME="Ypsilon"

matrix:
  allow_failures:
    - env: SCHEME="Larceny"
    - env: SCHEME="SagittariusScheme"
    - env: SCHEME="Ypsilon"

sudo: false
dist: trusty

addons:
  apt:
    packages:
      # Larceny
      - libc6:i386
      # Sagittarius and GNU Guile
      - libgc-dev
      # GNU Guile
      - libunistring-dev

language: c

cache:
  ccache: true
  directories:
    - $HOME/opt

os:
  - linux

compiler:
  - gcc

before_script:
  # Install Akku.scm and dependencies
  - gpg --keyserver pool.sks-keyservers.net --recv-keys 08272FBB54EEB5072D5BA930E33E61A2E9B8C3A2
  - curl -A "$TRAVIS_REPO_SLUG" -LO "https://akku.weinholt.se/get-akku.sh{,.sig}"
  - gpg --verify get-akku.sh.sig get-akku.sh && bash get-akku.sh
  - ~/bin/akku install
  - export SCHEME_LIBRARY_PATH=$PWD/.akku/lib
  # Install scheme-ci
  - wget https://github.com/weinholt/scheme-ci/archive/master.zip -O scheme-ci-master.zip
  - unzip scheme-ci-master.zip
  - eval "$(CC=gcc-4.8 INSTALL_TARGET=$HOME/opt scheme-ci-master/install-scheme.sh $SCHEME)"

script:
  - tests/aes.sps
  - tests/arcfour.sps
  - tests/base.sps
  - tests/blowfish.sps
  - tests/der.sps
  - tests/des.sps
  - tests/dh.sps
  - tests/dns.sps
  - tests/dsa.sps
  - tests/ecdsa.sps
  - tests/otr.sps
  - tests/password.sps
  - tests/punycode.sps
  - tests/ssh-kex.sps
  - tests/random-art.sps
  - tests/rsa.sps
